spring:
  application:
   name: configurationService
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jahnavilatha/book-author-config.git
          clone-on-start: true

          skip-ssl-validation: true

server:
  port: 8888
logging:
  pattern:
    console: "%msg%n"