spring:
  application:
  name: RegistryService
server:
  port: 8761
eureka:
  client:
  register-with-eureka: false

  fetch-registry: false

  server:
  wait-time-in-ms-when-sync-empty: 500
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-uri:
#    path: /swagger-ui.html #http://localhost:8761/swagger-ui/index.html
#management:
#  endpoints:
#    web:
#      exposure:
#      include: "*"   #http://localhost:8100/acutator/

